version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: java_pro
    restart: always
    environment:
      POSTGRES_DB: webAppDb
      POSTGRES_USER: ezvya
      POSTGRES_PASSWORD: ezvya2247
    ports:
      - '5432:5432'